# fly.toml app configuration file generated for mineru-api
app = "mineru-api"
primary_region = "iad"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  interval = "60s"
  grace_period = "180s"
  method = "get"
  path = "/docs"
  protocol = "http"
  timeout = "30s"
  tls_skip_verify = false

[machine]
  memory = "32gb"
  cpu_kind = "performance"
  cpus = 8
  gpu_kind = "a100-40gb"

